http:
    addr: "127.0.0.1:8080"
    log-level: "debug"

security:
    secret: "YOUR_SECRET"
    secp256k1:
        private: "./prikey"

paper-engine:
    engine: "fs"
    # max attachment size
    # unit of measurement: bits
    # example 134217728 = 128MB
    max-attachment-size: 134217728
    fs:
        repo: "paper.repo/"